package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

const configTemplate = `# edge-proxy configuration
# Generated by ` + "`edge-proxy init`" + `. Edit fields marked with TODO before starting.

admin:
  bind: "127.0.0.1:8080"   # bind 0.0.0.0 only if you trust the network
  username: admin
  password_hash: ""        # TODO: run "edge-proxy gen-passwd <plain>" and paste here

acme:
  email: ""                # TODO: your Let's Encrypt contact email
  directory: "https://acme-v02.api.letsencrypt.org/directory"
  challenge_port: 5002

probe:
  health_path: "/"
  timeout_seconds: 3
  fail_threshold: 3
  recover_threshold: 2

alert:
  dedup_window_minutes: 60
  dingtalk:
    webhook: ""            # TODO: dingtalk robot webhook url, or leave empty to disable
    secret: ""             # TODO: dingtalk signing secret, or leave empty
  telegram:
    bot_token: ""          # TODO: telegram bot token, or leave empty to disable
    chat_id: ""            # TODO: telegram chat id, or leave empty

paths:
  data_dir: "/var/lib/edge-proxy"
  nginx_conf_dir: "/etc/nginx/conf.d"
  nginx_reload_cmd: "systemctl reload nginx"
`

func initCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Print a config.yaml template to stdout",
		Long:  "Print an annotated YAML template. Redirect to /etc/edge-proxy/config.yaml and edit TODO fields.",
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Print(configTemplate)
			return nil
		},
	}
}
